# Generated by Django 4.1.7 on 2023-02-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('productPrice', models.TextField(max_length=255)),
                ('lotSize', models.CharField(max_length=255)),
                ('productDescription', models.CharField(max_length=555)),
                ('productImage', models.ImageField(upload_to='productImages/')),
            ],
        ),
    ]
