# Generated by Django 4.1.7 on 2023-02-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bottleVolume',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
