# Generated by Django 4.1.7 on 2023-02-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_product_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogThumb',
            field=models.ImageField(default='', upload_to='./blogImage/'),
            preserve_default=False,
        ),
    ]
